apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-test
  annotations:
    tekton.dev/title: "Go Unit Test Task"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:9117a23423cc18eeb14e43221b61bbeafa0e6c364166514553241365eaf6b083
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/usr/bin/env sh
        go mod vendor
        go test -buildvcs=false $(go list ./... | grep -v /storage/ | grep -v /client/ )
